export interface StudyMetadata {
  study_id: string;
  study_start: number;
  study_end: number;
}

export interface Event {
  id: string;
  ts: number;
  label: string;
  autogenerated?: boolean;
}

export type StudyId = string;

export interface AssessmentStudyResponse {
  metadata: StudyMetadata;
  signals: import("../../signal/model/types").Signals;
  events: Event[];
}

export function createStudyId(id: string): StudyId {
  if (!id || id.length === 0) {
    throw new Error("StudyId cannot be empty");
  }
  return id as StudyId;
}
