import { Event, AssessmentStudyResponse } from "../types"
import { mockStudy } from "../mockData"

// TO FIX: ad-hoc API module returning fresh arrays/objects on each call,
// without caching, and without properly wiring AbortSignal.
// Variable latency can cause race conditions if studyId changes during fetch.

export async function fetchStudy(
  studyId: string,
  _signal?: AbortSignal
): Promise<AssessmentStudyResponse> {
  // TO FIX: Variable latency to expose race conditions + AbortSignal ignored
  const latency = Math.random() * 800 + 200 // 200-1000ms random delay
  await new Promise((r) => setTimeout(r, latency))

  // Generate slightly different data per studyId to make race conditions visible
  const studyOffset = studyId.includes("002")
    ? 10
    : studyId.includes("003")
    ? 20
    : 0

  const clone: AssessmentStudyResponse = {
    metadata: {
      ...mockStudy.metadata,
      study_id: studyId || mockStudy.metadata.study_id,
    },
    signals: {
      hr: mockStudy.signals.hr
        ? {
            ...mockStudy.signals.hr,
            values: mockStudy.signals.hr.values.map((v) => v + studyOffset),
          }
        : undefined,
      spo2: mockStudy.signals.spo2
        ? {
            ...mockStudy.signals.spo2,
            values: mockStudy.signals.spo2.values.map((v) => v - studyOffset),
          }
        : undefined,
      resp: mockStudy.signals.resp
        ? {
            ...mockStudy.signals.resp,
            values: [...mockStudy.signals.resp.values],
          }
        : undefined,
      position: mockStudy.signals.position
        ? {
            ...mockStudy.signals.position,
            values: [...mockStudy.signals.position.values],
          }
        : undefined,
    },
    events: mockStudy.events.map((e: Event) => ({ ...e })),
  }
  return clone
}

export async function fetchEvents(_studyId: string): Promise<Event[]> {
  // Simulate polling and events mutability
  await new Promise((r) => setTimeout(r, 250))
  return mockStudy.events.map((e: Event) => ({
    ...e,
    autogenerated: Math.random() > 0.3, // randomize to force re-renders
  }))
}
