import { AssessmentStudyResponse } from "./domains/study/model/types";

export const mockStudy: AssessmentStudyResponse = {
  metadata: {
    study_id: "demo-study-001",
    study_start: 0,
    study_end: 600, // seconds
  },
  signals: {
    hr: {
      timestamps: Array.from({ length: 601 }, (_, i) => i),
      values: Array.from(
        { length: 601 },
        (_, i) => 60 + Math.round(8 * Math.sin(i / 12))
      ),
    },
    spo2: {
      timestamps: Array.from({ length: 601 }, (_, i) => i),
      values: Array.from(
        { length: 601 },
        (_, i) => 94 + Math.round(3 * Math.cos(i / 20))
      ),
    },
    resp: {
      timestamps: Array.from({ length: 601 }, (_, i) => i),
      values: Array.from({ length: 601 }, (_, i) =>
        Math.round(10 + 3 * Math.sin(i / 8))
      ),
    },
    position: {
      timestamps: Array.from({ length: 601 }, (_, i) => i),
      values: Array.from({ length: 601 }, (_, i) => (i % 120 < 60 ? 0 : 1)),
    },
  },
  events: [
    { id: "e1", ts: 120, label: "Desat", autogenerated: true },
    { id: "e2", ts: 240, label: "Resp", autogenerated: true },
    { id: "e3", ts: 300, label: "Desat", autogenerated: false },
  ],
};
