export interface SignalSeries {
  timestamps?: number[]
  values: number[]
  start_time?: number
  sample_rate?: number
}

export interface Signals {
  hr?: SignalSeries
  spo2?: SignalSeries
  resp?: SignalSeries
  position?: SignalSeries
}

export interface Event {
  id: string
  ts: number
  label: string
  autogenerated?: boolean
}

export interface AssessmentStudyResponse {
  metadata: {
    study_id: string
    study_start: number
    study_end: number
  }
  signals: Signals
  events: Event[]
}

export interface GlobalState {
  studyId: string
  loading: boolean
  error?: string

  // TO FIX: TOO MANY GLOBAL STATE. mix server data + UI state all in one big object
  signals: Signals
  visibleSignals: Signals // TO FIX: full copies instead of simple ids
  events: Event[]

  // TO FIX: derived values stored globally
  yMin?: number
  yMax?: number

  chartWidth: number
  chartHeight: number
  autoScale: boolean

  lastFetchedAt?: number
  pollMs: number

  // TO FIX: time window for "zoom" (also stored globally)
  currentStartSec: number
  currentEndSec: number
}
